# Generated by Django 5.0.3 on 2024-04-05 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_student_gender_alter_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
    ]
